import os
import getpass
import asyncio
from post_graph import AsyncPostGraph

# Auto-detect local connection string
username = getpass.getuser()
default_url = f"postgresql://{username}@localhost:5432/postgres"
db_url = os.environ.get("DATABASE_URL", default_url)

# Toggle Schema-Per-Realm isolation via environment variables
use_schema_per_realm = os.environ.get("SCHEMA_PER_REALM", "false").lower() == "true"


async def main():
    print("=" * 60)
    print("GREEK GODS GRAPH PLAYGROUND (AUTOGENERATED IDS)")
    print(f"Schema-Per-Realm Isolation: {use_schema_per_realm}")
    print("=" * 60)
    print(f"Connecting to database: {db_url}")

    client = AsyncPostGraph(dsn=db_url, schema_per_realm=use_schema_per_realm)
    await client.connect()

    realm = "pantheon"

    # Clean start: drop existing tables
    if use_schema_per_realm:
        print(f"\n[+] Dropping old schema '{realm}' to start fresh...")
        await client._execute(f'DROP SCHEMA IF EXISTS "{realm}" CASCADE;')
    else:
        print("\n[+] Dropping old tables to start fresh...")
        await client._execute('DROP TABLE IF EXISTS "godsTOgods_data" CASCADE;')
        await client._execute('DROP TABLE IF EXISTS "godsTOgods_audit" CASCADE;')
        await client._execute('DROP TABLE IF EXISTS "godsTOgods" CASCADE;')
        await client._execute('DROP TABLE IF EXISTS "gods_data" CASCADE;')
        await client._execute('DROP TABLE IF EXISTS "gods_audit" CASCADE;')
        await client._execute('DROP TABLE IF EXISTS "gods" CASCADE;')

    # 1. Create tables
    print(f"[+] Creating 'gods' vertex table and 'godsTOgods' edge table (realm={realm})...")
    await client.create_vertex_table("gods", realm=realm)
    await client.create_edge_table("godsTOgods", from_vertex_table="gods", to_vertex_table="gods", realm=realm)

    # 2. Add Deities (Vertices) with Autogenerated IDs
    print("[+] Populating Greek deities with autogenerated IDs...")

    # Primordials
    chaos = await client.add_vertex("gods", realm, payload={"role": "Primordial Void", "title": "Chaos"})
    uranus = await client.add_vertex("gods", realm, payload={"role": "God of the Sky", "title": "Uranus"})
    gaia = await client.add_vertex("gods", realm, payload={"role": "Goddess of the Earth", "title": "Gaia"})

    # Titans
    cronus = await client.add_vertex("gods", realm, payload={"role": "King of the Titans, God of Time", "title": "Cronus"})
    rhea = await client.add_vertex("gods", realm, payload={"role": "Queen of the Titans, Goddess of Motherhood", "title": "Rhea"})

    # Olympians (Generation 1)
    zeus = await client.add_vertex("gods", realm, payload={"role": "King of the Gods, God of Sky & Thunder", "title": "Zeus"})
    hera = await client.add_vertex("gods", realm, payload={"role": "Queen of the Gods, Goddess of Marriage", "title": "Hera"})
    poseidon = await client.add_vertex("gods", realm, payload={"role": "God of the Sea", "title": "Poseidon"})
    hades = await client.add_vertex("gods", realm, payload={"role": "God of the Underworld", "title": "Hades"})
    demeter = await client.add_vertex("gods", realm, payload={"role": "Goddess of Agriculture", "title": "Demeter"})
    hestia = await client.add_vertex("gods", realm, payload={"role": "Goddess of the Hearth", "title": "Hestia"})

    # Olympians (Generation 2)
    ares = await client.add_vertex("gods", realm, payload={"role": "God of War", "title": "Ares"})
    hephaestus = await client.add_vertex("gods", realm, payload={"role": "God of Fire & Metallurgy", "title": "Hephaestus"})
    athena = await client.add_vertex("gods", realm, payload={"role": "Goddess of Wisdom & Strategy", "title": "Athena"})
    apollo = await client.add_vertex("gods", realm, payload={"role": "God of Music, Sun & Archery", "title": "Apollo"})
    artemis = await client.add_vertex("gods", realm, payload={"role": "Goddess of the Hunt & Moon", "title": "Artemis"})
    hermes = await client.add_vertex("gods", realm, payload={"role": "Messenger God, God of Trade & Thieves", "title": "Hermes"})
    dionysus = await client.add_vertex("gods", realm, payload={"role": "God of Wine & Festivity", "title": "Dionysus"})

    # 3. Link Deities (Edges)
    print("[+] Building relationship graph with autogenerated edge IDs...")
    # Primordial origins
    await client.add_edge("godsTOgods", realm, from_id=uranus.id, to_id=chaos.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=gaia.id, to_id=chaos.id, relation_type="child_of")

    # Titans parentage
    await client.add_edge("godsTOgods", realm, from_id=cronus.id, to_id=uranus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=cronus.id, to_id=gaia.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=rhea.id, to_id=uranus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=rhea.id, to_id=gaia.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=cronus.id, to_id=rhea.id, relation_type="spouse_of")

    # Olympians Gen 1 parentage
    olympians_g1 = [zeus, hera, poseidon, hades, demeter, hestia]
    for olympian in olympians_g1:
        await client.add_edge("godsTOgods", realm, from_id=olympian.id, to_id=cronus.id, relation_type="child_of")
        await client.add_edge("godsTOgods", realm, from_id=olympian.id, to_id=rhea.id, relation_type="child_of")

    # Olympian marriages
    zeus_hera_edge = await client.add_edge("godsTOgods", realm, from_id=zeus.id, to_id=hera.id, relation_type="spouse_of")

    # Olympians Gen 2 parentage
    await client.add_edge("godsTOgods", realm, from_id=ares.id, to_id=zeus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=ares.id, to_id=hera.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=hephaestus.id, to_id=zeus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=hephaestus.id, to_id=hera.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=athena.id, to_id=zeus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=apollo.id, to_id=zeus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=artemis.id, to_id=zeus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=hermes.id, to_id=zeus.id, relation_type="child_of")
    await client.add_edge("godsTOgods", realm, from_id=dionysus.id, to_id=zeus.id, relation_type="child_of")

    print("\n" + "=" * 50)
    print("PLAYGROUND QUERIES & TRAVERSALS")
    print("=" * 50)

    # A. Get a God's title & role
    zeus_db = await client.get_vertex("gods", realm, zeus.id)
    print(f"[Query A] Loaded Vertex Zeus:")
    print(f"    Autogenerated ID: {zeus_db.id}")
    print(f"    Name:  {zeus_db.payload.get('title')}")
    print(f"    Role:  {zeus_db.payload.get('role')}")

    # B. Who are Zeus's parents? (Traverse outward via child_of relationship)
    print(f"\n[Query B] Zeus's Parents (Traversing outward via 'child_of' relations):")
    parent_steps = await zeus_db.to("godsTOgods")
    for step in parent_steps:
        if step.edge.relation_type == "child_of":
            parent = step.vertex()
            print(f"    -> Parent ID: {parent.id}")
            print(f"       Name:      {parent.payload.get('title')}")

    # C. Who are Cronus's children? (Reverse traverse incoming 'child_of' relations)
    print(f"\n[Query C] Cronus's Children (Reverse traversing incoming 'child_of' relations):")
    cronus_db = await client.get_vertex("gods", realm, cronus.id)
    child_steps = await cronus_db.from_("godsTOgods")
    for step in child_steps:
        if step.edge.relation_type == "child_of":
            child = step.vertex()
            print(f"    -> Child ID: {child.id}")
            print(f"       Name:     {child.payload.get('title')}")

    # D. Lineage path: Ares back to Chaos
    print(f"\n[Query D] Lineage path from Ares back to Chaos:")
    path_info = await client.shortest_path(
        realm=realm,
        start_table="gods",
        start_id=ares.id,
        target_table="gods",
        target_id=chaos.id,
        edge_tables=["godsTOgods"],
        max_depth=5
    )
    if path_info:
        readable_names = []
        for step in path_info['path']:
            table, v_id = step.split(":", 1)
            v = await client.get_vertex(table, realm, v_id)
            readable_names.append(v.payload.get("title"))
        print(f"    Path found (Depth {path_info['depth']}): {' -> '.join(readable_names)}")
    else:
        print("    No path found.")

    # E. Test Cycle Protection (Try to make Zeus a child of Ares)
    print(f"\n[Query E] Attempting to add cyclic edge (Zeus -> Ares as child_of with check_cycle=True):")
    try:
        await client.add_edge(
            table_name="godsTOgods",
            realm=realm,
            from_id=zeus.id,
            to_id=ares.id,
            relation_type="child_of",
            check_cycle=True
        )
        print("    [-] Error: Cyclic edge was incorrectly allowed!")
    except Exception as e:
        print(f"    [OK] Cycle check prevented loop: {e}")

    # F. Showcase Append-Only Data Tables (gods_data & godsTOgods_data)
    print(f"\n[Query F] Showcasing Append-Only Data Tables ('gods_data' & 'godsTOgods_data'):")
    print(f"    -> Appending historical mythological events to Zeus in 'gods_data'...")
    await zeus_db.add_data({"event": "Titanomachy", "outcome": "Overthrew Titans", "artifact": "Thunderbolt"})
    await zeus_db.add_data({"event": "Gigantomachy", "outcome": "Defeated Giants", "artifact": "Aegis"})

    zeus_history = await zeus_db.get_data()
    print(f"    Loaded {len(zeus_history)} historical events for Zeus:")
    for rec in zeus_history:
        print(f"      -> [Data ID {rec.data_id}] Time: {rec.timestamp.strftime('%Y-%m-%d %H:%M:%S')} | Event: {rec.payload.get('event')} ({rec.payload.get('outcome')})")

    print(f"    -> Appending marriage record event to Zeus <-> Hera edge in 'godsTOgods_data'...")
    await zeus_hera_edge.add_data({"event": "Sacred Union", "location": "Mount Olympus", "gift": "Golden Apples"})
    edge_history = await zeus_hera_edge.get_data()
    print(f"    Loaded {len(edge_history)} edge data record for Zeus-Hera marriage:")
    for rec in edge_history:
        print(f"      -> [Data ID {rec.data_id}] Event: {rec.payload.get('event')} at {rec.payload.get('location')}")

    await client.close()

    print("\n" + "=" * 50)
    print("READY TO PLAY!")
    print("=" * 50)
    if use_schema_per_realm:
        print(f"The schema namespace '{realm}' is fully populated and remains active.")
        print("You can connect to Postgres directly and query the schema-isolated tables:")
        print(f"  psql -d postgres -c \"SELECT id, payload->>'title' as name FROM \\\"{realm}\\\".gods;\"")
        print(f"  psql -d postgres -c \"SELECT from_id, relation_type, to_id FROM \\\"{realm}\\\".\\\"godsTOgods\\\";\"")
    else:
        print("The tables 'gods' and 'godsTOgods' are fully populated and remain active.")
        print("You can run your own Python queries or connect to Postgres directly:")
        print(f"  psql -d postgres -c \"SELECT id, payload->>'title' as name FROM gods;\"")
        print(f"  psql -d postgres -c \"SELECT from_id, relation_type, to_id FROM \\\"godsTOgods\\\";\"")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
